apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - image: "172.168.161.6/library/myrepo:busybox"
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      name: busybox
  restartPolicy: Always
