apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
  - name: simple-pod
    image: "k8s.gcr.io/busybox"
    volumeMounts:
    - name: block-vol
      mountPath: "/mnt/volume1"
    command: ["sleep", "1000000"]
  volumes:
    - name: block-vol
      persistentVolumeClaim:
        claimName: block-pvc-r1-2g
